console.log(window);
console.log(this);
console.log(document);
console.log(document.head);
console.log(dociment.body);
document.title="DOM";
console.log(window.location);
console.log(window.screen.availHeight);
console.log(window.screen.availWidth);